@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12

!pragma useVerticalIf on
start
:User executes <i>delivery add</i> command;

partition DeliveryAddCommand {
    if () then ([else])
        :CommandException: User Not Authenticated;
        stop
    ( [user logged in]) elseif () then ([else])
        :CommandException: Invalid Customer ID;
        stop
    ( [customer ID found]) elseif () then ([else])
        :CommandException: Invalid Delivery Date;
        stop
    else ( [expected Delivery date is today or after today])
    endif
    : Add Delivery;
}

stop

@enduml
