@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":CustomerDeleteCommandParser" as CustomerDeleteCommandParser LOGIC_COLOR
participant "d:CustomerDeleteCommand" as CustomerDeleteCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("customer delete 1")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("customer delete 1")
activate AddressBookParser

create CustomerDeleteCommandParser
AddressBookParser -> CustomerDeleteCommandParser
activate CustomerDeleteCommandParser

CustomerDeleteCommandParser --> AddressBookParser
deactivate CustomerDeleteCommandParser

AddressBookParser -> CustomerDeleteCommandParser : parse("1")
activate CustomerDeleteCommandParser

create CustomerDeleteCommand
CustomerDeleteCommandParser -> CustomerDeleteCommand
activate CustomerDeleteCommand

CustomerDeleteCommand --> CustomerDeleteCommandParser : d
deactivate CustomerDeleteCommand

CustomerDeleteCommandParser --> AddressBookParser : d
deactivate CustomerDeleteCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
CustomerDeleteCommandParser -[hidden]-> AddressBookParser
destroy CustomerDeleteCommandParser

AddressBookParser --> LogicManager : d
deactivate AddressBookParser

LogicManager -> CustomerDeleteCommand : execute()
activate CustomerDeleteCommand

CustomerDeleteCommand -> Model : deleteCustomer(1)
activate Model

Model --> CustomerDeleteCommand
deactivate Model

create CommandResult
CustomerDeleteCommand -> CommandResult
activate CommandResult

CommandResult --> CustomerDeleteCommand
deactivate CommandResult

CustomerDeleteCommand --> LogicManager : result
deactivate CustomerDeleteCommand

[<--LogicManager
deactivate LogicManager
@enduml
