@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12

!pragma useVerticalIf on
start
:User enters <i>delivery note</i> command;
partition DeliveryStatusCommandParser {
    if () then ([Null arguments provided])
        :NullPointerException: Args cannot be Null;
        stop
    else ([Not Null])
    endif
    : Tokenize Arguments with Note prefix;
    if () then ([Prefix Not Present or Preamble not Empty])
        :ParseException: Invalid Command Format;
        stop
    elseif () then ([Duplicate Prefix])
        :ParseException: Duplicate Prefix;
        stop
    elseif () then ([Invalid Delivery ID])
        :ParseException: Invalid Delivery ID;
         stop
    elseif () then ([Invalid Note])
        :ParseException: Invalid Note;
        stop
    else ([Valid ID and Note Provided])
    endif
    :Create and Execute DeliveryCreateNoteCommand;
}

partition DeliveryCreateNoteCommand {
    if () then ([User Not Logged In])
        :CommandException: User Not Authenticated;
        stop
    elseif () then ([Delivery ID Not Found])
        :CommandException: Invalid Delivery;
        stop
    else ()
    endif
    : Create Delivery with new note;
    : Replace Selected Delivery with Created Delivery;
    : Refresh Displayed Delivery List;
    : Return CommandResult;
}

stop

@enduml
