@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model as ModelPackage <<Rectangle>>{

Class "<<interface>>\nReadOnlyUserPrefs" as ReadOnlyUserPrefs
Class "<<interface>>\nModel" as Model
Class AddressBook<Customer>
Class DeliveryBook<Delivery>
Class ModelManager
Class UserPrefs

Class Customer



Class Delivery

Class User

Class ListItem

}

Class I<<Hidden>> #FFFFFF
Class H<<Hidden>> #FFFFFF
Class J<<Hidden>> #FFFFFF
Class K<<Hidden>> #FFFFFF


Class HiddenOutside<<HIDDEN>> #FFFFFF
HiddenOutside ..> Model



Model -right-> ReadOnlyUserPrefs

ModelManager .up.|> Model
ModelManager -up-> "1" DeliveryBook
ModelManager -up-> "1" AddressBook
'
UserPrefs .up.|> ReadOnlyUserPrefs

ModelManager -right-> "~* uiList" ListItem
ListItem -[hidden]down-> J
ModelManager -right-> "1" UserPrefs

ModelManager -up-> "1" User
User -[hidden]right-> K
ModelManager -left-> "~* filteredCustomers" Customer
Customer-[hidden]left--> H

ModelManager -down-> "~* filteredDeliveries" Delivery
Delivery -[hidden]left--> I

ModelManager -down-> "~* sortedDeliveries" Delivery

'


'
'
'


'
'

'

'
'


@enduml
