@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage as StoragePackage {

package "UserPrefs Storage" #F4F6F6{
Class "<<interface>>\nUserPrefsStorage" as UserPrefsStorage
Class JsonUserPrefsStorage
}


Class "<<interface>>\nStorage" as Storage
Class StorageManager
Class "<<interface>>\nBookStorage<T>" as BookStorage
Class "<<interface>>\nBookStorage<Customer>" as BookStorageCustomer
Class "{abstract}\nBookStorageWithReference<T, R>" as BookStorageWithReference
Class "{abstract}\nBookStorageWithReference<Customer, Delivery>" as BookStorageWithReferenceDeliveryCustomer
BookStorageWithReference -|> BookStorage


package "AddressBook Storage" #F4F6F6{
Class JsonAddressBookStorage
Class JsonSerializableAddressBook
Class JsonAdaptedCustomer
}

package "DeliveryBook Storage" #F4F6F6{
Class JsonDeliveryBookStorage
Class JsonSerializableDeliveryBook
Class JsonAdaptedDelivery
}

}

Class HiddenOutside<<HIDDEN>> #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -left-> "1" UserPrefsStorage
StorageManager -down-> "1" BookStorageWithReference
StorageManager -down-> "1" BookStorage

Storage -|> UserPrefsStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
BookStorageCustomer .up.> BookStorage
JsonAddressBookStorage .up.|> BookStorageCustomer
JsonAddressBookStorage ..> JsonSerializableAddressBook
JsonSerializableAddressBook --> "*" JsonAdaptedCustomer


BookStorageWithReferenceDeliveryCustomer .up..> BookStorageWithReference
JsonDeliveryBookStorage -up--|> BookStorageWithReferenceDeliveryCustomer
JsonDeliveryBookStorage ..> JsonSerializableDeliveryBook
JsonSerializableDeliveryBook --> "*" JsonAdaptedDelivery

@enduml
