@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
!pragma useVerticalIf on
start
:User executes logout command;
:Parse command string;

if () then ([user is already logged out])
    :CommandException: Already Logged Out;
    stop
else ([else])
    :User logout command is executed successfully.
    User is now logged out.;
    :Hide Customer and Delivery List;
endif

stop
@enduml
