@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package User as ModelPackage <<Rectangle>>{
Class User
Class Username
Class Password

Class I #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside .down.> User

User --> "1" Username
User --> "1" Password


@enduml
