@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12

!pragma useVerticalIf on
start
:User enters <i>delivery list --status COMPLETED \n <i> --customer 1</i> \n <i> --date TODAY </i> \n <i> --sort ASC </i>;
partition DeliveryListCommandParser {
    if () then ([else])
        :ParseException: Invalid Command Format;
        stop
        else ([empty preamble])
        endif

       if () then ([status provided])
           :Parse delivery status;
       else ([else])
       endif

       if () then ([customer id provided])
           :Parse customer id;

       else ([else])
       endif

       if () then ([date provided])

           if () then ([date is "TODAY"])
               :Get today's date;

           else ([else])
            :Parse date;
           endif

       else ([else])
        endif

          if () then ([sort provided])
                   :Parse sort;

               else ([else])
               :Set sort by descending;
               endif

}

partition DeliveryListCommand {
    if () then ([else])
        :CommandException: User Not Authenticated;
        stop
    else ([user logged in])

    if () then ([status provided])
        :Add status filter;
    else ([else])
    endif

    if () then ([customer id provided])
        :Add customer id filter;
    else ([else])
    endif

    if () then ([date provided])
        :Add expected delivery date filter;
    else ([else])
    endif
        : Filter delivery list according to filters;
     if () then ([sort provided])
            :Add sort by provided sort;
        else ([else])
        :Add sort by the default descending;
        endif
        : Sort by expected delivery date;
        : Return CommandResult;
    endif

}

stop

@enduml
