@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12

!pragma useVerticalIf on
start
:User enters <i>delivery list --status completed \n <i> --sort asc </i> command;
partition DeliveryListParser {
    if () then ([else])
        :ParseException: Invalid Command Format;
        stop
    ([none-empty arguments provided]) elseif () then ([else])
        :ParseException: Invalid Delivery Status;
        stop
    ([sort provided]) elseif () then ([else])
        :ParseException: Invalid Sort;
        stop
    else ([valid Sort])
        :Create and Execute DeliveryListCommand;
        endif
}

partition DeliveryListCommand {
    if () then ([else])
        :CommandException: User Not Authenticated;
        stop
    else ([user logged in])

    if () then ([Status Provided])
        :Filter deliveries by status;
    else ([else])
    endif

    if () then ([Customer ID Provided])
        :Filter deliveries by customer id;
    else ([else])
    endif

    if () then ([date Provided])
        :Filter deliveries by date;
    else ([else])
    endif
        : Sort by delivery date according to sort order;
        : Refresh Displayed Delivery List;
        : Return CommandResult;
    endif

}

stop

@enduml
