@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12

!pragma useVerticalIf on
start
:User enters <i>delivery list --status completed \n <i> --sort asc </i> command;
partition DeliveryListParser {
    if (Check Arguments Present) then ([Empty arguments provided])
        :ParseException: Invalid Command Format;
        stop
    elseif (Parse DeliveryStatus) then ([Invalid Status])
        :ParseException: Invalid Delivery Status;
        stop
    elseif (Parse Sort) then ([Invalid Sort])
        :ParseException: Invalid Sort;
        stop
    endif
    :Create and Execute DeliveryListCommand;
}

partition DeliveryListCommand {
    if (User Logged in?) then ([Not Logged In])
        :CommandException: User Not Authenticated;
        stop
    endif

    if (Check status present) then ([Status Provided])
        :Filter deliveries by status;
    elseif (Check customer id present) then ([Customer ID Provided])
        :Filter deliveries by customer id;
    elseif (Check data present) then ([Data Provided])
        :Filter deliveries by date;
    endif
        : List deliveries filtered ;
        : Sort by sort order;
        : Refresh Displayed Delivery List;
        : Return CommandResult;
}

stop

@enduml
